<table>
    <tr>
        <td  style="background-color:#ffffff;" width="18%"><img src="..\images\qworld.jpg"  align="left"></td>
        <td style="background-color:#ffffff;" width="*"></td>
        <td  style="background-color:#ffffff;vertical-align:text-top;" width="21%"><img src="..\images\qpoland.jpg" align="right"></td>  
        <td  style="background-color:#ffffff;vertical-align:text-top;" width="19%" ><img src="..\images\qlatvia.jpg" align="right"></td>  
    </tr>
    <tr><td colspan="4" align="right" style="color:#777777;background-color:#ffffff;font-size:12px;">
        prepared by Anastasija Trizna and Oskar Słowik
    </td></tr>
    <tr><td colspan="4" align="right" style="color:#bbbbbb;background-color:#ffffff;font-size:11px;font-style:italic;">
        This cell contains some macros. If there is a problem with displaying mathematical formulas, please run this cell to load these macros.
    </td></tr>
</table>
$ \newcommand{\bra}[1]{\langle #1|} $
$ \newcommand{\ket}[1]{|#1\rangle} $
$ \newcommand{\braket}[2]{\langle #1|#2\rangle} $
$ \newcommand{\dot}[2]{ #1 \cdot #2} $
$ \newcommand{\biginner}[2]{\left\langle #1,#2\right\rangle} $
$ \newcommand{\mymatrix}[2]{\left( \begin{array}{#1} #2\end{array} \right)} $
$ \newcommand{\myvector}[1]{\mymatrix{c}{#1}} $
$ \newcommand{\myrvector}[1]{\mymatrix{r}{#1}} $
$ \newcommand{\mypar}[1]{\left( #1 \right)} $
$ \newcommand{\mybigpar}[1]{ \Big( #1 \Big)} $
$ \newcommand{\sqrttwo}{\frac{1}{\sqrt{2}}} $
$ \newcommand{\dsqrttwo}{\dfrac{1}{\sqrt{2}}} $
$ \newcommand{\onehalf}{\frac{1}{2}} $
$ \newcommand{\donehalf}{\dfrac{1}{2}} $
$ \newcommand{\hadamard}{ \mymatrix{rr}{ \sqrttwo & \sqrttwo \\ \sqrttwo & -\sqrttwo }} $
$ \newcommand{\vzero}{\myvector{1\\0}} $
$ \newcommand{\vone}{\myvector{0\\1}} $
$ \newcommand{\vhadamardzero}{\myvector{ \sqrttwo \\  \sqrttwo } } $
$ \newcommand{\vhadamardone}{ \myrvector{ \sqrttwo \\ -\sqrttwo } } $
$ \newcommand{\myarray}[2]{ \begin{array}{#1}#2\end{array}} $
$ \newcommand{\X}{ \mymatrix{cc}{0 & 1 \\ 1 & 0}  } $
$ \newcommand{\Z}{ \mymatrix{rr}{1 & 0 \\ 0 & -1}  } $
$ \newcommand{\Htwo}{ \mymatrix{rrrr}{ \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} } } $
$ \newcommand{\CNOT}{ \mymatrix{cccc}{1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0} } $
$ \newcommand{\norm}[1]{ \left\lVert #1 \right\rVert } $

Classical coding theory tends to concentrate on <i>linear codes</i>, a subclass of all possible codes with a particular relation between codewords.

While working with linear codes, there are two matrices that are primary used to describing linear codes in mathematical notation. 

<h3>Generator matrix</h3>

The <b>generator matrix </b> ($G$), is a $k×n$ matrix.
<li>$k$ row vectors with dimension $n$; 
<li>$k$ - number of encoded bits for codeword; $n$ - number of bits for codeword).

$G$ generates the codewords $c$ of a linear code by taking binary string $m$ as an input:
<center>$c=mG$</center>

The form for a generator matrix is:
<center>$G=[I$<sub>k</sub>$|P]$</center>

Where $I$<sub>k</sub> is $k×k$ identity matrix.\
And $P$ is $k×(n-k)$ which is not an identity, this is the part that allows to correct errors. 

<h3>Parity check matrix</h3>

$H$ is <b>parity check</b> matrix with size  $(n-k)×n$.\
It can be used to test if a given bit string is a valid codeword, since $Hc = 0$ iff $c$ is a codeword.

Since any codeword $c$ has the form $mG$, $Hc = HGm = m0 = 0$, and $H$ <b>annihilates</b> any codeword.

A generator matrix can be used to construct the parity check matrix for a code and vice versa:
<center>$H=[-P$<sup>T</sup>$|I$<sub>(n-k)</sub>$]$</center>

Where $-P$<sup>T</sup> is minus tranpose of matrix $P$. While working with classical codes, we can ignore minus sign.

The transpose of a matrix is obtained by interchanging rows and columns.\
For example, the second row becomes the new second column, and third column becomes the new third row.

In parity check matrix each column <b>must be unique</b>.

<h3>Task 1: (7,4) Hamming code</h3>

(7,4) Hamming code generator matrix is:
$$
G=\mymatrix{rrrr}{1 & 0 & 0 & 0 & 1 & 1 & 0 \\ 0 & 1 & 0 & 0 & 0 & 1 & 1 \\ 0 & 0 & 1 & 0 & 1 & 0 & 1 \\ 0 & 0 & 0 & 1 & 1 & 1 & 1}.
$$

<b>Create parity check matrix $H$.

In [1]:
#
# your code is here
#

In [2]:
#Solution

import numpy as np

#P part of generator matrix
P = [
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
]

n=7 #number of bits in codeword
k=4 #number of data bits

#our H matrix will have size mxn, where m=n-k
m=n-k

# Creating left part of parity check matrix (PT)
# First create the PT as a zero matrix with mxk dimensions
PT=[]
for i in range(m):
    PT.append([])
    for j in range(k):
        PT[i].append(0)
        
# filling parity check matrix with PT
for i in range(k):
    for j in range(m):
        PT[j][i]=P[i][j] 

        
# Creating right side of parity check matrix which is identity matrix with size mxm
I = np.identity(m) #numpy function to create identity matrix

# Contatinating two matrices to get H
H=np.concatenate((PT,I),axis=1) # to concatinate column-wise you need to specify axis=1

# Print out result
for i in range(len(H)):
    print(H[i])

[1. 0. 1. 1. 1. 0. 0.]
[1. 1. 0. 1. 0. 1. 0.]
[0. 1. 1. 1. 0. 0. 1.]


<b>Use generator $G$ to produce code word $c$ for message $m=0011$.</b>
    
Note that you need to keep your result <i>binary</i>. To do so, apply <b>mod2</b> operator if you see any other numbers than $0$ or $1$ in your matrices.

In [3]:
#
# your code is here
#

In [5]:
#Solution

G = [
    [1, 0, 0, 0, 1, 1, 0],
    [0, 1, 0, 0, 0, 1, 1],
    [0, 0, 1, 0, 1, 0, 1],
    [0, 0, 0, 1, 1, 1, 1]
]

#M as a vector
m=[0, 0, 1, 1]

c=np.matmul(m, G)

#applying mod2 operator
cBin=np.mod(c, 2)

print("Message", m)
print("Codeword", cBin)

Message [0, 0, 1, 1]
Codeword [0 0 1 1 0 1 0]


<b>Verify if your created codeword $w$ is a valid by applying transpose of parity check matrix.</b>
    
If your code word is valid, it should annihilate with parity check matrix:
<center>$w$$H$<sup>T</sup>=0

In [5]:
#
# your code is here
#

In [9]:
#Solution
# First create thanspose of parity check matrix
HT=[]
for i in range(7):
    HT.append([])
    for j in range(3):
        HT[i].append(0)

for i in range(3):
    for j in range(7):
        HT[j][i]=H[i][j] 

#Multiplying codeword with a parity matrix
check=np.matmul(c,HT)

#applying mod2 operator
checkBin=np.mod(check, 2)

print("Check bits for codeword", cBin, "is", checkBin)

Check bits for codeword [0 0 1 1 0 1 0] is [0. 0. 0.]


<b>Is binary string $0011011$ a valid codeword?

In [7]:
#
# your code is here
#

In [10]:
binary=[0, 0, 1, 1, 0, 1, 1]

check=np.matmul(binary,HT)
checkBin=np.mod(check, 2)

print("Check bits for codeword", binary, "is", checkBin)

Check bits for codeword [0, 0, 1, 1, 0, 1, 1] is [0. 0. 1.]


<h3>Error syndrome</h3>





The result you get after verifying if the codeword is valid by calculating $c$$H$<sup>T</sup> (or $c$<sup>T</sup>$H$, it works both ways) is called <b>error syndrome</b> ($s$) for $c$.

<b>$c$ is a codeword of a linear code iff $s=0$.

If $s≠0$, we can conclude that there is an error in codeword $c$ and say exactly which bit contains an error by <b>decoding</b> the syndrome.

Syndrome decoding is a highly effective method used while working with noisy channels, allowed by the linearity of the code. 

For syndrome decoding, we will need $s$ calculated as $s=cH$<sup>T</sup> and out parity matrix $H$.

In [21]:
print("Message with error, m:", binary)

print("Error syndrome, s:")
for i in range(len(checkBin)):
    print(checkBin[i])
    
print("Parity check matrix, H:")
for i in range(len(H)):
    print(H[i])

Message with error, m: [0, 0, 1, 1, 0, 1, 1]
Error syndrome, s:
0.0
0.0
1.0
Parity check matrix, H:
[1. 0. 1. 1. 1. 0. 0.]
[1. 1. 0. 1. 0. 1. 0.]
[0. 1. 1. 1. 0. 0. 1.]


By looking and $s$ and comparing it with $H$, we can conclude that error occured in last bit.

Followed by the property of parity check matrix, that each column of matrix $H$ is unique, for each location of an error we will get different error syndrome. 

<h3>Task 2: (8,4) Hamming code [optional] </h3>

(8,4) Hamming code is an extended version of (7,4) Hamming code.
The addition of an overall parity bit it allows to detect (but not correct) double-bit errors.

<b>What is [n, k, d] for (8,4) Hamming code?</b>

Sometimes, when creating generator and parity check matrices, it is easier to make a parity check matrix first.\
Parity check matrix has a size $[(n-k)×n]$ and structure $[P$<sup>T</sup>$|I$<sub>(n-k)</sub>$]$.

<b>Create parity check matrix for (8,4) Hamming code.</b>
<li>First, create $I$, identity matrix with size $[(n-k)×(n-k)]$.
<li>Then, create empty matrix $P$<sup>T</sup>, where size is $[n-(n-k)×(n-k)]$.
<li>Fill $P$<sup>T</sup> such that each column is unique. Each column should contain more than two binary $1$ entries.
<li>Concatinate $P$<sup>T</sup> and $I$ matrices.

In [22]:
#
# your code is here
#

In [48]:
#Solution

#Creating I
n=8
k=4
m=n-k
# Creating right side of parity check matrix which is identity matrix with size mxm
I = np.identity(m) #numpy function to create identity matrix

#Creating PT with size lxm
l=n-m
PT=[]
for i in range(l):
    PT.append([])
    for j in range(m):
        PT[i].append(0)

#1st PT column
PT[0][0]=1
PT[1][0]=1
PT[2][0]=1
PT[3][0]=1

#2nd PT column
PT[0][1]=1
PT[1][1]=1
PT[2][1]=1
PT[3][1]=0

#3rd PT column
PT[0][2]=1
PT[1][2]=1
PT[2][2]=0
PT[3][2]=1

#4th PT column
PT[0][3]=1
PT[1][3]=0
PT[2][3]=1
PT[3][3]=1

#Creating H by concatinating PT and I matrices

H=np.concatenate((PT,I),axis=1) # to concatinate column-wise you need to specify axis=1

# Print out result
for i in range(len(H)):
    print(H[i])

[1. 1. 1. 1. 1. 0. 0. 0.]
[1. 1. 1. 0. 0. 1. 0. 0.]
[1. 1. 0. 1. 0. 0. 1. 0.]
[1. 0. 1. 1. 0. 0. 0. 1.]


<b>Create generator matrix for (8,4) Hamming code.</b>\
Generator matrix has a size $[k×n]$ and stricture $[I$<sub>k</sub>$|P]$.
<li>We already have $P$<sup>T</sup>, so to get $P$ you need to apply transpose to $(P$<sup>T</sup>$)$<sup>T</sup>.
<li>Then, create $I$ with size $[k×k]$
<li>Concatinate $P$ and $I$

In [49]:
#
# your code is here
#

In [50]:
#Solution
#Applying transpose to PT

# Creating left part of parity check matrix (PT)
# First create the PT as a zero matrix with mxk dimensions
P=[]
for i in range(m):
    P.append([])
    for j in range(l):
        P[i].append(0)
        
# filling parity check matrix with PT
for i in range(l):
    for j in range(m):
        P[j][i]=PT[i][j] 
        
#Creating identity matrix
Ig = np.identity(k) #numpy function to create identity matrix

#Concatinating matrices
G=np.concatenate((P,Ig),axis=1) 

<b>What is a codeword for $0101$ message?</b>

In [55]:
#
# your code is here
#

In [57]:
#Solution
m1=[0, 1, 0, 1]

c1=np.matmul(m1, G)
c1Bin=np.mod(c1, 2)

print("Message", m1)
print("Codeword", c1Bin)

Message [0, 1, 0, 1]
Codeword [0. 1. 0. 1. 0. 1. 0. 1.]


<b>What is a codeword for $1111$ message?</b>

In [53]:
#
# your code is here
#

In [54]:
#Solution
m2=[1, 1, 1, 1]

c2=np.matmul(m2, G)

c2Bin=np.mod(c2, 2)

print("Message", m2)
print("Codeword", c2Bin)

Message [1, 1, 1, 1]
Codeword [0. 1. 1. 1. 1. 1. 1. 1.]


<b>One error.\
We flip bit #7. Is $01010111$ a valid codeword?

In [64]:
#
# your code is here
#

In [60]:
#Solution
c3=[0, 1, 0, 1, 0, 1, 1, 1]

# First create thanspose of parity check matrix
HT=[]
for i in range(8):
    HT.append([])
    for j in range(4):
        HT[i].append(0)

for i in range(4):
    for j in range(8):
        HT[j][i]=H[i][j] 

#Multiplying codeword with a parity matrix
s3=np.matmul(c3,HT)

#applying mod2 operator
s3Bin=np.mod(check, 2)

print("Syndrome for codeword", c3, "is", s3Bin)

Check bits for codeword [0, 1, 0, 1, 0, 1, 1, 1] is [0. 0. 1. 0.]


<b>Two errors.\
We flip bits #5 and #7. Is $01011111$ a valid codeword?

In [ ]:
#
# your code is here
#

In [63]:
#Solution
c4=[0, 1, 0, 1, 1, 1, 1, 1]

#Multiplying codeword with a parity matrix
s4=np.matmul(c4,HT)

#applying mod2 operator
s4Bin=np.mod(check, 2)

print("Syndrome for codeword", c4, "is", s4Bin)

Syndrome for codeword [0, 1, 0, 1, 1, 1, 1, 1] is [0. 0. 1. 0.]


<b>Why we get the same syndrome when we flip one bit and when we flip two bits?

In (8,4) Hamming code encoded bit string is: $p1 p2 b1 p4 b2 b3 b4 p8$\
Where $p8=p$<sub>1</sub> ⊕ $p$<sub>2</sub> ⊕ $b$<sub>1</sub> ⊕ $p$<sub>4</sub> ⊕ $b$<sub>2</sub> ⊕ $b$<sub>3</sub> ⊕ $b$<sub>4</sub>\
If the parity bit indicates an error, single error correction will indicate the error location.\
If the parity bit is correct, then single error correction will indicate the XOR of two error locations.\
If the locations are equal ("no error") then a double bit error either has not occurred, or has cancelled itself out.\
Otherwise, a double bit error has occurred.